# 标准包
apache2=2.4.54
php=
java-11-openjdk=11.0.22
awscli=2.13.7

# 自定义安装（不参与卸载）
custom:nodejs=| curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash - && sudo yum install -y nodejs
custom:docker=| curl -fsSL https://get.docker.com | sh
